# Copyright 2022 99Cloud, Inc. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# flake8: noqa
# fmt: off

"""default_intersection_rse

Revision ID: 033631578e40
Revises: 41d3255a429a
Create Date: 2023-02-27 11:11:02.487896

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "033631578e40"
down_revision = "41d3255a429a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("camera", sa.Column("is_default", sa.Boolean(), nullable=False))
    op.add_column("intersection", sa.Column("is_default", sa.Boolean(), nullable=False))
    op.add_column("lidar", sa.Column("is_default", sa.Boolean(), nullable=False))
    op.add_column("map", sa.Column("is_default", sa.Boolean(), nullable=False))
    op.add_column("radar", sa.Column("is_default", sa.Boolean(), nullable=False))
    op.add_column("rsu", sa.Column("is_default", sa.Boolean(), nullable=False))
    op.add_column("spat", sa.Column("is_default", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("spat", "is_default")
    op.drop_column("rsu", "is_default")
    op.drop_column("radar", "is_default")
    op.drop_column("map", "is_default")
    op.drop_column("lidar", "is_default")
    op.drop_column("intersection", "is_default")
    op.drop_column("camera", "is_default")
    # ### end Alembic commands ###
