# Copyright 2022 99Cloud, Inc. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# flake8: noqa
# fmt: off

"""add spat

Revision ID: 0cc3f6cfa16b
Revises: ec54a0a8f04a
Create Date: 2022-09-19 13:23:43.668907

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0cc3f6cfa16b"
down_revision = "ec54a0a8f04a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "spat",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("create_time", sa.DateTime(), nullable=False),
        sa.Column("update_time", sa.DateTime(), nullable=False),
        sa.Column("intersection_id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("spat_ip", sa.String(length=15), nullable=False),
        sa.Column("point", sa.String(length=15), nullable=False),
        sa.Column("online_status", sa.Boolean(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("phase_id", sa.String(length=64), nullable=False),
        sa.Column("light", sa.String(length=15), nullable=False),
        sa.Column("rsu_id", sa.Integer(), nullable=True),
        sa.Column("timing", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["rsu_id"],
            ["rsu.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("intersection_id", "phase_id"),
    )
    op.create_index(op.f("ix_spat_id"), "spat", ["id"], unique=False)
    op.create_index(op.f("ix_spat_intersection_id"), "spat", ["intersection_id"], unique=False)
    op.create_index(op.f("ix_spat_name"), "spat", ["name"], unique=False)
    op.create_index(op.f("ix_spat_phase_id"), "spat", ["phase_id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_spat_phase_id"), table_name="spat")
    op.drop_index(op.f("ix_spat_name"), table_name="spat")
    op.drop_index(op.f("ix_spat_intersection_id"), table_name="spat")
    op.drop_index(op.f("ix_spat_id"), table_name="spat")
    op.drop_table("spat")
    # ### end Alembic commands ###
