"""radar_camera

Revision ID: 26c910b0342f
Revises: 556f61d01468
Create Date: 2023-04-17 11:21:52.089414

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "26c910b0342f"
down_revision = "556f61d01468"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "radar_camera",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("create_time", sa.DateTime(), nullable=False),
        sa.Column("update_time", sa.DateTime(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("sn", sa.String(length=64), nullable=False),
        sa.Column("lng", sa.Float(), nullable=False),
        sa.Column("lat", sa.Float(), nullable=False),
        sa.Column("elevation", sa.Float(), nullable=False),
        sa.Column("towards", sa.Float(), nullable=False),
        sa.Column("point", sa.String(length=15), nullable=False),
        sa.Column("pole", sa.String(length=15), nullable=False),
        sa.Column("video_stream_address", sa.String(length=255), nullable=False),
        sa.Column("radar_camera_ip", sa.String(length=15), nullable=False),
        sa.Column("rsu_id", sa.Integer(), nullable=True),
        sa.Column("status", sa.Boolean(), nullable=False),
        sa.Column("desc", sa.String(length=255), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["rsu_id"],
            ["rsu.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_radar_camera_id"), "radar_camera", ["id"], unique=False)
    op.create_index(op.f("ix_radar_camera_name"), "radar_camera", ["name"], unique=True)
    op.create_index(op.f("ix_radar_camera_sn"), "radar_camera", ["sn"], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_radar_camera_sn"), table_name="radar_camera")
    op.drop_index(op.f("ix_radar_camera_name"), table_name="radar_camera")
    op.drop_index(op.f("ix_radar_camera_id"), table_name="radar_camera")
    op.drop_table("radar_camera")
    # ### end Alembic commands ###
