"""edge_area

Revision ID: 3182956c1749
Revises: e26a1ff54061
Create Date: 2023-03-14 14:38:05.958739

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "3182956c1749"
down_revision = "e26a1ff54061"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("edge_node", sa.Column("area_code", sa.String(length=64), nullable=True))
    op.create_foreign_key("edgenode_fk_area", "edge_node", "area", ["area_code"], ["code"])
    op.add_column("system_config", sa.Column("area_code", sa.String(length=64), nullable=True))
    op.create_foreign_key("edge_fk_area", "system_config", "area", ["area_code"], ["code"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("edge_fk_area", "system_config", type_="foreignkey")
    op.drop_column("system_config", "area_code")
    op.drop_constraint("edgenode_fk_area", "edge_node", type_="foreignkey")
    op.drop_column("edge_node", "area_code")
    # ### end Alembic commands ###
