"""add_algo

Revision ID: 3c8c89cfb09a
Revises: 5a9e7ac60afb
Create Date: 2022-12-23 14:15:19.198000

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "3c8c89cfb09a"
down_revision = "5a9e7ac60afb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "algo_module",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("create_time", sa.DateTime(), nullable=False),
        sa.Column("update_time", sa.DateTime(), nullable=False),
        sa.Column("module", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("module"),
    )
    op.create_index(op.f("ix_algo_module_id"), "algo_module", ["id"], unique=False)
    op.create_table(
        "algo_name",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("create_time", sa.DateTime(), nullable=False),
        sa.Column("update_time", sa.DateTime(), nullable=False),
        sa.Column("module", sa.String(length=64), nullable=True),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("enable", sa.Boolean(), nullable=False),
        sa.Column("module_path", sa.String(length=64), nullable=False),
        sa.Column("in_use", sa.String(length=64), nullable=True),
        sa.ForeignKeyConstraint(
            ["module"],
            ["algo_module.module"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name", "module"),
    )
    op.create_index(op.f("ix_algo_name_id"), "algo_name", ["id"], unique=False)
    op.create_index(op.f("ix_algo_name_name"), "algo_name", ["name"], unique=False)
    op.create_table(
        "algo_version",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("create_time", sa.DateTime(), nullable=False),
        sa.Column("update_time", sa.DateTime(), nullable=False),
        sa.Column("algo", sa.String(length=64), nullable=True),
        sa.Column("version", sa.String(length=64), nullable=False),
        sa.Column("version_path", sa.String(length=64), nullable=True),
        sa.ForeignKeyConstraint(
            ["algo"],
            ["algo_name.name"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("algo", "version"),
    )
    op.create_index(op.f("ix_algo_version_id"), "algo_version", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_algo_version_id"), table_name="algo_version")
    op.drop_table("algo_version")
    op.drop_index(op.f("ix_algo_name_name"), table_name="algo_name")
    op.drop_index(op.f("ix_algo_name_id"), table_name="algo_name")
    op.drop_table("algo_name")
    op.drop_index(op.f("ix_algo_module_id"), table_name="algo_module")
    op.drop_table("algo_module")
    # ### end Alembic commands ###
