# Copyright 2022 99Cloud, Inc. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# flake8: noqa
# fmt: off

"""intersection_map

Revision ID: 4004b21768c2
Revises: 033631578e40
Create Date: 2023-03-06 14:20:02.744087

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4004b21768c2'
down_revision = '033631578e40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_map_rsu_id', table_name='map_rsu')
    op.drop_table('map_rsu')
    op.drop_index('ix_map_id', table_name='map')
    op.drop_index('ix_map_name', table_name='map')
    op.drop_table('map')
    op.add_column('intersection', sa.Column('map_data', sa.JSON(), nullable=False))
    op.add_column('intersection', sa.Column('bitmap_filename', sa.String(length=64), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('intersection', 'bitmap_filename')
    op.drop_column('intersection', 'map_data')
    op.create_table('map',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('create_time', mysql.DATETIME(), nullable=False),
    sa.Column('update_time', mysql.DATETIME(), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('desc', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('lat', mysql.FLOAT(), nullable=False),
    sa.Column('lng', mysql.FLOAT(), nullable=False),
    sa.Column('data', mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'), nullable=True),
    sa.Column('intersection_code', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('bitmap_filename', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('is_default', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['intersection_code'], ['intersection.code'], name='intersection_fk_code_map', onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_map_name', 'map', ['name'], unique=False)
    op.create_index('ix_map_id', 'map', ['id'], unique=False)
    op.create_table('map_rsu',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('create_time', mysql.DATETIME(), nullable=False),
    sa.Column('update_time', mysql.DATETIME(), nullable=False),
    sa.Column('map_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('rsu_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('status', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['map_id'], ['map.id'], name='map_rsu_ibfk_1'),
    sa.ForeignKeyConstraint(['rsu_id'], ['rsu.id'], name='map_rsu_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_map_rsu_id', 'map_rsu', ['id'], unique=False)
    # ### end Alembic commands ###
