"""edge_site

Revision ID: 46267393359d
Revises: 59efdface736
Create Date: 2023-04-11 14:02:02.327435

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "46267393359d"
down_revision = "59efdface736"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "edge_site",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("create_time", sa.DateTime(), nullable=False),
        sa.Column("update_time", sa.DateTime(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("edge_site_dandelion_endpoint", sa.String(length=64), nullable=False),
        sa.Column("area_code", sa.String(length=64), nullable=True),
        sa.Column("desc", sa.String(length=255), nullable=True),
        sa.Column("center_dandelion_endpoint", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(["area_code"], ["area.code"], name="edgesite_fk_area"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(op.f("ix_edge_site_id"), "edge_site", ["id"], unique=False)
    op.drop_index("ix_edge_node_rsu_esn", table_name="edge_node_rsu")
    op.drop_index("ix_edge_node_rsu_id", table_name="edge_node_rsu")
    op.drop_index("ix_edge_node_rsu_name", table_name="edge_node_rsu")
    op.drop_table("edge_node_rsu")
    op.drop_index("ix_edge_node_id", table_name="edge_node")
    op.drop_index("ix_edge_node_name", table_name="edge_node")
    op.drop_table("edge_node")
    op.add_column("system_config", sa.Column("edge_site_id", sa.Integer(), nullable=True))
    op.add_column(
        "system_config", sa.Column("edge_site_external_ip", sa.String(length=64), nullable=True)
    )
    op.add_column(
        "system_config",
        sa.Column("center_dandelion_endpoint", sa.String(length=255), nullable=True),
    )
    op.drop_constraint("edge_fk_area", "system_config", type_="foreignkey")
    op.drop_column("system_config", "name")
    op.drop_column("system_config", "area_code")
    op.drop_column("system_config", "local_ip")
    op.drop_column("system_config", "node_id")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "system_config",
        sa.Column("node_id", mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    )
    op.add_column("system_config", sa.Column("local_ip", mysql.VARCHAR(length=64), nullable=True))
    op.add_column("system_config", sa.Column("area_code", mysql.VARCHAR(length=64), nullable=True))
    op.add_column("system_config", sa.Column("name", mysql.VARCHAR(length=255), nullable=True))
    op.create_foreign_key("edge_fk_area", "system_config", "area", ["area_code"], ["code"])
    op.drop_column("system_config", "center_dandelion_endpoint")
    op.drop_column("system_config", "edge_site_external_ip")
    op.drop_column("system_config", "edge_site_id")
    op.create_table(
        "edge_node",
        sa.Column("id", mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
        sa.Column("create_time", mysql.DATETIME(), nullable=False),
        sa.Column("update_time", mysql.DATETIME(), nullable=False),
        sa.Column("name", mysql.VARCHAR(length=64), nullable=False),
        sa.Column("ip", mysql.VARCHAR(length=64), nullable=False),
        sa.Column("area_code", mysql.VARCHAR(length=64), nullable=True),
        sa.ForeignKeyConstraint(["area_code"], ["area.code"], name="edgenode_fk_area"),
        sa.PrimaryKeyConstraint("id"),
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_index("ix_edge_node_name", "edge_node", ["name"], unique=False)
    op.create_index("ix_edge_node_id", "edge_node", ["id"], unique=False)
    op.create_table(
        "edge_node_rsu",
        sa.Column("id", mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
        sa.Column("create_time", mysql.DATETIME(), nullable=False),
        sa.Column("update_time", mysql.DATETIME(), nullable=False),
        sa.Column(
            "edge_node_id", mysql.INTEGER(display_width=11), autoincrement=False, nullable=True
        ),
        sa.Column("name", mysql.VARCHAR(length=64), nullable=False),
        sa.Column("esn", mysql.VARCHAR(length=64), nullable=False),
        sa.Column(
            "location", mysql.LONGTEXT(charset="utf8mb4", collation="utf8mb4_bin"), nullable=False
        ),
        sa.Column(
            "edge_rsu_id", mysql.INTEGER(display_width=11), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(["edge_node_id"], ["edge_node.id"], name="edge_node_rsu_ibfk_2"),
        sa.PrimaryKeyConstraint("id"),
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_index("ix_edge_node_rsu_name", "edge_node_rsu", ["name"], unique=False)
    op.create_index("ix_edge_node_rsu_id", "edge_node_rsu", ["id"], unique=False)
    op.create_index("ix_edge_node_rsu_esn", "edge_node_rsu", ["esn"], unique=False)
    op.drop_index(op.f("ix_edge_site_id"), table_name="edge_site")
    op.drop_table("edge_site")
    # ### end Alembic commands ###
