"""add enabled field in endpoint

Revision ID: 556f61d01468
Revises: 94cf9906bb71
Create Date: 2023-04-12 14:10:58.954762

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "556f61d01468"
down_revision = "94cf9906bb71"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("endpoint", sa.Column("enabled", sa.Boolean(), nullable=False))
    op.drop_index("name", table_name="endpoint")
    op.drop_column("endpoint", "version")
    op.drop_column("endpoint", "name")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("endpoint", sa.Column("name", mysql.VARCHAR(length=64), nullable=False))
    op.add_column("endpoint", sa.Column("version", mysql.VARCHAR(length=64), nullable=True))
    op.create_index("name", "endpoint", ["name"], unique=False)
    op.drop_column("endpoint", "enabled")
    # ### end Alembic commands ###
