"""add service_type

Revision ID: 59efdface736
Revises: c7a29fc8d3b3
Create Date: 2023-04-07 15:14:15.680519

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "59efdface736"
down_revision = "c7a29fc8d3b3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "service_type",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("create_time", sa.DateTime(), nullable=False),
        sa.Column("update_time", sa.DateTime(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(op.f("ix_service_type_id"), "service_type", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_service_type_id"), table_name="service_type")
    op.drop_table("service_type")
    # ### end Alembic commands ###
