"""add service & endpoint

Revision ID: 94cf9906bb71
Revises: 46267393359d
Create Date: 2023-04-11 18:00:22.139949

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "94cf9906bb71"
down_revision = "46267393359d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "service",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("create_time", sa.DateTime(), nullable=False),
        sa.Column("update_time", sa.DateTime(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("type_id", sa.Integer(), nullable=True),
        sa.Column("vendor", sa.String(length=64), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["type_id"],
            ["service_type.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(op.f("ix_service_id"), "service", ["id"], unique=False)
    op.create_table(
        "endpoint",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("create_time", sa.DateTime(), nullable=False),
        sa.Column("update_time", sa.DateTime(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("service_id", sa.Integer(), nullable=True),
        sa.Column("version", sa.String(length=64), nullable=True),
        sa.Column("url", sa.String(length=256), nullable=False),
        sa.ForeignKeyConstraint(
            ["service_id"],
            ["service.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(op.f("ix_endpoint_id"), "endpoint", ["id"], unique=False)
    op.create_table(
        "endpoint_metadata",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("create_time", sa.DateTime(), nullable=False),
        sa.Column("update_time", sa.DateTime(), nullable=False),
        sa.Column("endpoint_id", sa.Integer(), nullable=True),
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("value", sa.String(length=256), nullable=True),
        sa.ForeignKeyConstraint(
            ["endpoint_id"],
            ["endpoint.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("endpoint_id", "key", name="idx_endpoint_key"),
    )
    op.create_index(op.f("ix_endpoint_metadata_id"), "endpoint_metadata", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_endpoint_metadata_id"), table_name="endpoint_metadata")
    op.drop_table("endpoint_metadata")
    op.drop_index(op.f("ix_endpoint_id"), table_name="endpoint")
    op.drop_table("endpoint")
    op.drop_index(op.f("ix_service_id"), table_name="service")
    op.drop_table("service")
    # ### end Alembic commands ###
