# Copyright 2022 99Cloud, Inc. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# flake8: noqa
# fmt: off

"""add rsi dnp

Revision ID: acafe01d1190
Revises: a298aee508d5
Create Date: 2022-07-14 09:37:39.522025

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'acafe01d1190'
down_revision = 'a298aee508d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rsi_dnp',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.Column('update_time', sa.DateTime(), nullable=False),
    sa.Column('msg_id', sa.String(length=255), nullable=False),
    sa.Column('sec_mark', sa.Integer(), nullable=False),
    sa.Column('veh_id', sa.String(length=255), nullable=False),
    sa.Column('ref_pos', sa.JSON(), nullable=False),
    sa.Column('drive_suggestion', sa.JSON(), nullable=False),
    sa.Column('path_guidance', sa.JSON(), nullable=False),
    sa.Column('info', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rsi_dnp_id'), 'rsi_dnp', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rsi_dnp_id'), table_name='rsi_dnp')
    op.drop_table('rsi_dnp')
    # ### end Alembic commands ###
