"""camera_radar_add_enabled

Revision ID: b8dbd693ca39
Revises: 3c8c89cfb09a
Create Date: 2022-12-28 14:02:51.687474

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b8dbd693ca39"
down_revision = "3c8c89cfb09a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("camera", sa.Column("enabled", sa.Boolean(), nullable=True))
    op.add_column("radar", sa.Column("enabled", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("radar", "enabled")
    op.drop_column("camera", "enabled")
    # ### end Alembic commands ###
