"""system_config_add_ip

Revision ID: c7a29fc8d3b3
Revises: d4eee55189b5
Create Date: 2023-03-23 17:19:00.722677

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "c7a29fc8d3b3"
down_revision = "d4eee55189b5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("system_config", sa.Column("local_ip", sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("system_config", "local_ip")
    # ### end Alembic commands ###
