# Copyright 2022 99Cloud, Inc. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# flake8: noqa
# fmt: off

"""change camera stream_url length

Revision ID: ca29ab3a1fc7
Revises: 0cc3f6cfa16b
Create Date: 2022-09-28 11:26:05.028310

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'ca29ab3a1fc7'
down_revision = '0cc3f6cfa16b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    connection = op.get_bind()
    if connection.engine.name == 'mysql':
        op.alter_column('camera', 'stream_url', type_=sa.String(1024), nullable=False, default="")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    connection = op.get_bind()
    if connection.engine.name == 'mysql':
        op.alter_column('camera', 'stream_url', type_=sa.String(255), nullable=False, default="")
    # ### end Alembic commands ###
