# Copyright 2022 99Cloud, Inc. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# flake8: noqa
# fmt: off

"""Add RSU additional info

Revision ID: cb28fbd7424f
Revises: ca6e02bc2a7b
Create Date: 2022-07-20 18:24:02.567677

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'cb28fbd7424f'
down_revision = 'ca6e02bc2a7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rsu', sa.Column('bias_x', sa.Float(), nullable=True))
    op.add_column('rsu', sa.Column('bias_y', sa.Float(), nullable=True))
    op.add_column('rsu', sa.Column('rotation', sa.Float(), nullable=True))
    op.add_column('rsu', sa.Column('reverse', sa.Boolean(), nullable=True))
    op.add_column('rsu', sa.Column('scale', sa.Float(), nullable=True))
    op.add_column('rsu', sa.Column('lane_info', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rsu', 'lane_info')
    op.drop_column('rsu', 'scale')
    op.drop_column('rsu', 'reverse')
    op.drop_column('rsu', 'rotation')
    op.drop_column('rsu', 'bias_y')
    op.drop_column('rsu', 'bias_x')
    # ### end Alembic commands ###
