"""area

Revision ID: d4eee55189b5
Revises: 3182956c1749
Create Date: 2023-03-16 14:53:25.216881

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "d4eee55189b5"
down_revision = "3182956c1749"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("edge_node_rsu_ibfk_1", "edge_node_rsu", type_="foreignkey")
    op.drop_column("edge_node_rsu", "area_code")
    op.drop_constraint("map_ibfk_1", "map", type_="foreignkey")
    op.drop_column("map", "address")
    op.drop_column("map", "area_code")
    op.drop_column("map", "lat")
    op.drop_column("map", "lng")
    op.drop_index("ix_rsi_event_address", table_name="rsi_event")
    op.drop_constraint("rsi_event_ibfk_1", "rsi_event", type_="foreignkey")
    op.drop_column("rsi_event", "address")
    op.drop_column("rsi_event", "area_code")
    op.drop_constraint("rsu_ibfk_1", "rsu", type_="foreignkey")
    op.drop_column("rsu", "address")
    op.drop_column("rsu", "area_code")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("rsu", sa.Column("area_code", mysql.VARCHAR(length=64), nullable=True))
    op.add_column(
        "rsu",
        sa.Column(
            "address",
            mysql.VARCHAR(length=255),
            nullable=False,
            comment="Installation specific location",
        ),
    )
    op.create_foreign_key("rsu_ibfk_1", "rsu", "area", ["area_code"], ["code"])
    op.add_column("rsi_event", sa.Column("area_code", mysql.VARCHAR(length=64), nullable=True))
    op.add_column("rsi_event", sa.Column("address", mysql.VARCHAR(length=64), nullable=False))
    op.create_foreign_key("rsi_event_ibfk_1", "rsi_event", "area", ["area_code"], ["code"])
    op.create_index("ix_rsi_event_address", "rsi_event", ["address"], unique=False)
    op.add_column("map", sa.Column("lng", mysql.FLOAT(), nullable=False))
    op.add_column("map", sa.Column("lat", mysql.FLOAT(), nullable=False))
    op.add_column("map", sa.Column("area_code", mysql.VARCHAR(length=64), nullable=True))
    op.add_column(
        "map",
        sa.Column(
            "address", mysql.VARCHAR(length=255), nullable=False, comment="specific location"
        ),
    )
    op.create_foreign_key("map_ibfk_1", "map", "area", ["area_code"], ["code"])
    op.add_column("edge_node_rsu", sa.Column("area_code", mysql.VARCHAR(length=64), nullable=True))
    op.create_foreign_key("edge_node_rsu_ibfk_1", "edge_node_rsu", "area", ["area_code"], ["code"])
    # ### end Alembic commands ###
