fixtures:
  - ConfigFixture
  - SampleDataFixture

defaults:
  ssl: False
  request_headers:
    content-type: application/json
    accept: application/json

vars:
  - &username 'gabbi_user'
  - &password 'dandelion'

tests:
  - name: create_user
    url: /api/omega/v1/users
    method: POST
    data:
      username: *username
      password: *password
      is_active: true
    status: 200
    response_json_paths:
      $.username: *username

  - name: user_login
    url: /api/omega/v1/login
    method: POST
    data:
      username: *username
      password: *password
    status: 200
    response_json_paths:
      $.token_type: bearer

  - name: create_rsu_model
    url: /api/omega/v1/rsu_models
    method: POST
    request_headers:
      Authorization: Bearer $HISTORY['user_login'].$RESPONSE['$.access_token']
    data:
      name: 蓝天SD726
      manufacturer: 蓝天科技
      desc: 蓝天726
    status: 201
    response_json_paths:
      $.name: 蓝天SD726
      $.manufacturer: 蓝天科技
      $.desc: 蓝天726

  - name: create_rsu
    url: /api/omega/v1/rsus
    method: POST
    request_headers:
      Authorization: Bearer $HISTORY['user_login'].$RESPONSE['$.access_token']
    data:
      rsuId: 'RSU_ID_01'
      rsuName: 'RSU_NAME_01'
      rsuEsn: 'RSU_ESN01'
      rsuIP: '192.168.0.101'
      intersectionCode: '32011501'
      rsuModelId: $HISTORY['create_rsu_model'].$RESPONSE['$.id']
      desc: 'test_rsu'
      lon: 118.8213963998263
      lat: 31.934846637757847
    status: 201
    response_json_paths:
      $.rsuId: 'RSU_ID_01'
      $.rsuName: 'RSU_NAME_01'
      $.rsuEsn: 'RSU_ESN01'
      $.rsuIP: '192.168.0.101'
      $.rsuModelId: $HISTORY['create_rsu_model'].$RESPONSE['$.id']

  - name: create_rsu_config_1
    url: /api/omega/v1/rsu_configs
    method: POST
    request_headers:
      Authorization: Bearer $HISTORY['user_login'].$RESPONSE['$.access_token']
    data:
      name: "nEvErMaTcH"
      bsm:
        sampleMode: "ByAll"
        sampleRate: 10
        upLimit: 1
      rsm:
        upLimit: 1
      map:
        upLimit: 1
      spat:
        upLimit: 1
      rsi:
        upFilters:
          -
            key: "1"
      rsus:
        - $HISTORY['create_rsu'].$RESPONSE['$.id']
    status: 201

  - name: create_rsu_config_2
    url: /api/omega/v1/rsu_configs
    method: POST
    request_headers:
      Authorization: Bearer $HISTORY['user_login'].$RESPONSE['$.access_token']
    data:
      name: "nEvErMaTcH_2"
      bsm:
        sampleMode: "ByAll"
        sampleRate: 10
        upLimit: 1
      rsm:
        upLimit: 1
      map:
        upLimit: 1
      spat:
        upLimit: 1
      rsi:
        upFilters:
          - key: "1"
      rsus:
        - $HISTORY['create_rsu'].$RESPONSE['$.id']
    status: 201

  - name: get_rsu_configs
    url: /api/omega/v1/rsu_configs
    method: GET
    request_headers:
      Authorization: Bearer $HISTORY['user_login'].$RESPONSE['$.access_token']
    query_parameters:
      pageNum: 1
      pageSize: 10
    status: 200

  - name: filter_rsu_configs
    url: /api/omega/v1/rsu_configs
    method: GET
    request_headers:
      Authorization: Bearer $HISTORY['user_login'].$RESPONSE['$.access_token']
    query_parameters:
      name: _
      pageNum: 1
      pageSize: 10
    status: 200
    response_json_paths:
      $.data.`len`: 1

  - name: get_once_rsu_config
    url: /api/omega/v1/rsu_configs/$HISTORY['create_rsu_config_1'].$RESPONSE['$.id']
    method: GET
    request_headers:
      Authorization: Bearer $HISTORY['user_login'].$RESPONSE['$.access_token']
    status: 200

  - name: edit_rsu_config
    url: /api/omega/v1/rsu_configs/$HISTORY['create_rsu_config_1'].$RESPONSE['$.id']
    method: PUT
    request_headers:
      Authorization: Bearer $HISTORY['user_login'].$RESPONSE['$.access_token']
    data:
      name: "config_2"
      bsm:
        sampleMode: "ByAll"
        sampleRate: 10
        upLimit: 2
      rsm:
        upLimit: 2
      map:
        upLimit: 2
      spat:
        upLimit: 2
      rsi:
        upFilters:
          -
            key: "2"
      rsus:
        - $HISTORY['create_rsu'].$RESPONSE['$.id']
    status: 200
    response_json_paths:
      $.bsmConfig.upLimit: 2
      $.rsmConfig.upLimit: 2
      $.mapConfig.upLimit: 2
      $.spatConfig.upLimit: 2

  - name: delete_rsu_config_1
    url: /api/omega/v1/rsu_configs/$HISTORY['create_rsu_config_1'].$RESPONSE['$.id']
    method: DELETE
    request_headers:
      Authorization: Bearer $HISTORY['user_login'].$RESPONSE['$.access_token']
    status: 204

  - name: delete_rsu_config_2
    url: /api/omega/v1/rsu_configs/$HISTORY['create_rsu_config_2'].$RESPONSE['$.id']
    method: DELETE
    request_headers:
      Authorization: Bearer $HISTORY['user_login'].$RESPONSE['$.access_token']
    status: 204

  - name: delete_rsu
    url: /api/omega/v1/rsus/$HISTORY['create_rsu'].$RESPONSE['$.id']
    method: DELETE
    request_headers:
      Authorization: Bearer $HISTORY['user_login'].$RESPONSE['$.access_token']
    status: 204

  - name: delete_rsu_model
    url: /api/omega/v1/rsu_models/$HISTORY['create_rsu_model'].$RESPONSE['$.id']
    method: DELETE
    request_headers:
      Authorization: Bearer $HISTORY['user_login'].$RESPONSE['$.access_token']
    status: 204

  - name: delete_user
    url: /api/omega/v1/users/$HISTORY['create_user'].$RESPONSE['$.id']
    method: DELETE
    request_headers:
      Authorization: Bearer $HISTORY['user_login'].$RESPONSE['$.access_token']
    status: 204
