fixtures:
  - ConfigFixture
  - SampleDataFixture

defaults:
  ssl: False
  request_headers:
    content-type: application/json
    accept: application/json

vars:
  - &username 'gabbi_user'
  - &password 'dandelion'

tests:
  - name: create_user
    url: /api/v1/users
    method: POST
    data:
      username: *username
      password: *password
      is_active: true
    status: 200
    response_json_paths:
      $.username: *username

  - name: user_login
    url: /api/v1/login
    method: POST
    data:
      username: *username
      password: *password
    status: 200
    response_json_paths:
      $.token_type: bearer

  - name: create_service_type
    url: /api/v1/service_types
    method: POST
    request_headers:
      Authorization: Bearer $HISTORY['user_login'].$RESPONSE['$.access_token']
    data:
      name: "service_type_A"
      description: "service_type_A_description"
    status: 201
    response_json_paths:
      $.name: "service_type_A"
      $.description: "service_type_A_description"

  - name: service_type_get
    url: /api/v1/service_types/$HISTORY['create_service_type'].$RESPONSE['$.id']
    method: GET
    request_headers:
      Authorization: Bearer $HISTORY['user_login'].$RESPONSE['$.access_token']
    status: 200
    response_json_paths:
      $.name: "service_type_A"
      $.description: "service_type_A_description"

  - name: service_type_list
    url: /api/v1/service_types
    method: GET
    request_headers:
      Authorization: Bearer $HISTORY['user_login'].$RESPONSE['$.access_token']
    status: 200
    response_json_paths:
      $.total: 1
      $.data[0].name: "service_type_A"
      $.data[0].description: "service_type_A_description"

  - name: service_type_update
    url: /api/v1/service_types/$HISTORY['create_service_type'].$RESPONSE['$.id']
    method: PUT
    request_headers:
      Authorization: Bearer $HISTORY['user_login'].$RESPONSE['$.access_token']
    data:
      name: "service_type_B"
      description: "service_type_B_description"
    status: 200

  - name: service_type_get
    url: /api/v1/service_types/$HISTORY['create_service_type'].$RESPONSE['$.id']
    method: GET
    request_headers:
      Authorization: Bearer $HISTORY['user_login'].$RESPONSE['$.access_token']
    status: 200
    response_json_paths:
      $.name: "service_type_B"
      $.description: "service_type_B_description"

  - name: delete_service_type
    url: /api/v1/service_types/$HISTORY['create_service_type'].$RESPONSE['$.id']
    method: DELETE
    request_headers:
      Authorization: Bearer $HISTORY['user_login'].$RESPONSE['$.access_token']
    status: 204

  - name: delete_user
    url: /api/v1/users/$HISTORY['create_user'].$RESPONSE['$.id']
    method: DELETE
    request_headers:
      Authorization: Bearer $HISTORY['user_login'].$RESPONSE['$.access_token']
    status: 204
