name: test

on:
  pull_request:
    branches:
      - 'master'

jobs:
            
  apitest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.8"]

    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}       
      - name: install pre
        shell: bash
        run: |
          sudo unalias cp 2>/dev/null || true
          sudo rm -rf openv2x-aio-master.tar.gz && wget https://openv2x.oss-ap-southeast-1.aliyuncs.com/deploy/master/openv2x-aio-master.tar.gz
          sudo rm -rf src && tar zxvf openv2x-aio-master.tar.gz
          sudo rm -rf /openv2x/data && sudo mkdir -pv /openv2x/data
          sudo cp -rf src/deploy/mysql /openv2x/data/
          sudo cp -rf src/deploy/lalserver /openv2x/data/
          sudo cp -f src/deploy/docker-compose-pre.yaml /tmp/docker-compose-pre.yaml
          sudo sed -i "s/8084/8085/" /tmp/docker-compose-pre.yaml
          sudo docker-compose -f /tmp/docker-compose-pre.yaml up -d
          sudo mkdir -pv /var/log/dandelion/
          sudo touch /var/log/dandelion/dandelion.log
          sudo mkdir -pv /etc/dandelion
          sudo cp src/deploy/dandelion/dandelion.conf /etc/dandelion/dandelion.conf
          sudo mkdir /openv2x/data/bitmap
          sudo cp map_bg.jpg /openv2x/data/bitmap/map_bg.jpg
      - name: Run dandelion
        shell: bash
        run: |
          pip install -r requirements.txt
          python setup.py install
          alembic upgrade head
          python tools/datainit.py
          pip install tox
          tox -e venv
          source .tox/venv/bin/activate
          sudo chmod -R 777 /var/log/
          uvicorn --reload --reload-dir dandelion --port 28300 --log-level debug dandelion.main:app --host 0.0.0.0 &
      - name: Run apitest
        shell: bash
        run: |
          pip install gabbi
          ls apitest/*.yaml | grep -v multi_node.yaml | xargs gabbi-run localhost:28300 --